import React, { createContext, useContext, useState } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    home: 'Home',
    bible: 'Bible',
    leaderboard: 'Leaderboard',
    wallet: 'Wallet',
    profile: 'Profile',
    
    // Settings
    settings: 'Settings',
    notifications: 'Notifications',
    darkMode: 'Dark Mode',
    language: 'Language',
    privacy: 'Privacy',
    about: 'About',
    
    // Profile
    editProfile: 'Edit Profile',
    appPreferences: 'App Preferences',
    personalInfo: 'Personal Information',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    dateOfBirth: 'Date of Birth',
    location: 'Location',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    changePhoto: 'Change Photo',
    
    // App Preferences
    readingPreferences: 'Reading Preferences',
    pushNotifications: 'Push Notifications',
    soundEffects: 'Sound Effects',
    autoBookmark: 'Auto Bookmark',
    enhancedReaderMode: 'Enhanced Reader Mode',
    dailyReadingReminders: 'Daily Reading Reminders',
    resetOptions: 'Reset Options',
    resetReadingProgress: 'Reset Reading Progress',
    clearAllBookmarks: 'Clear All Bookmarks',
    resetAllPreferences: 'Reset All Preferences',
    
    // Notifications
    notificationSettings: 'Notification Settings',
    readingReminders: 'Reading Reminders',
    achievements: 'Achievements',
    weeklyDigest: 'Weekly Digest',
    
    // About
    appVersion: 'App Version',
    rewardSystem: 'Reward System',
    howToEarn: 'How to Earn',
    leaderboardInfo: 'Leaderboard Information',
    
    // Success messages
    success: 'Success!',
    error: 'Error',
    profileUpdated: 'Profile updated successfully!',
    addressCopied: 'Address copied to clipboard!',
    pickDate: 'Pick a date',
    
    // Leaderboard page
    yourRank: 'Your Rank',
    topReadersThisMonth: 'Top Readers This Month',
    weeklyChallenge: 'Weekly Challenge',
    readFor7Hours: 'Read for 7 Hours This Week',
    hoursCompleted: 'hours completed',
    champion: 'Champion',
    runnerUp: 'Runner-up',
    thirdPlace: 'Third Place',
    fcBonus: 'FC Bonus',
    
    // Wallet page
    myWallet: 'My Wallet',
    walletBalance: 'Wallet Balance',
    faithChainTokens: 'FaithChain Tokens',
    send: 'Send',
    withdraw: 'Withdraw',
    totalEarned: 'Total Earned',
    tierStatus: 'Tier Status',
    recentTransactions: 'Recent Transactions',
    walletAddress: 'Wallet Address',
    autoGeneratedWallet: 'This is your auto-generated wallet address for receiving tokens.',
    bibleReading: 'Bible reading',
    minutes: 'minutes',
    dailyChallengeCompleted: 'Daily challenge completed',
    withdrawalToExternal: 'Withdrawal to external wallet',
    walletAddressCopied: 'Wallet address copied to clipboard!',
    
    // Books page
    books: 'Books',
    oldTestament: 'Old Testament',
    newTestament: 'New Testament',
    
    // About page
    faithChainBibleApp: 'FaithChain Bible App',
    version: 'Version',
    appDescription: 'FaithChain is a revolutionary Bible reading app that combines spiritual growth with blockchain rewards. Read, learn, and earn while deepening your faith journey.',
    dailyReadingRewards: 'Daily Reading Rewards',
    earnTokensDescription: 'Earn 10-50 FAITH tokens for completing daily Bible reading sessions',
    chapterCompletion: 'Chapter Completion',
    bonusTokensDescription: 'Get bonus tokens for finishing complete chapters and books',
    streakBonuses: 'Streak Bonuses',
    streakDescription: 'Maintain reading streaks for multiplied rewards up to 5x',
    gettingStarted: 'Getting Started',
    maximizingEarnings: 'Maximizing Earnings',
    createAccount: 'Create your account and complete profile setup',
    startReading: 'Start reading from any book in the Bible',
    completeReading: 'Complete at least 5 minutes of reading daily',
    trackProgress: 'Track your progress and earn rewards automatically',
    readConsistently: 'Read consistently every day to build streaks',
    completeChapters: 'Complete full chapters for bonus rewards',
    participateChallenges: 'Participate in community challenges',
    shareVerses: 'Share verses and invite friends',
    leaderboardDescription: 'The leaderboard showcases the most dedicated readers in our community. Rankings are based on:',
    totalReadingTime: 'Total Reading Time',
    chaptersCompleted: 'Chapters Completed',
    readingStreak: 'Reading Streak',
    communityEngagement: 'Community Engagement',
    weight: 'weight',
    monthlyRewards: 'Monthly Rewards',
    monthlyRewardsDescription: 'Top 10 users receive bonus FAITH tokens and exclusive badges!',
    contactSupport: 'Contact & Support',
    email: 'Email',
    website: 'Website',
    community: 'Community',
    joinDiscord: 'Join our Discord server for support and fellowship',
    
    // Descriptions
    pushNotificationsDesc: 'Receive notifications for reading reminders and achievements',
    soundEffectsDesc: 'Play sounds for interactions and achievements',
    autoBookmarkDesc: 'Automatically bookmark your reading progress',
    enhancedReaderModeDesc: 'Optimize text for comfortable reading',
    dailyReadingRemindersDesc: 'Get reminded to continue your daily reading'
  },
  
  fr: {
    // Navigation
    home: 'Accueil',
    bible: 'Bible',
    leaderboard: 'Classement',
    wallet: 'Portefeuille',
    profile: 'Profil',
    
    // Settings
    settings: 'Paramètres',
    notifications: 'Notifications',
    darkMode: 'Mode Sombre',
    language: 'Langue',
    privacy: 'Confidentialité',
    about: 'À Propos',
    
    // Profile
    editProfile: 'Modifier le Profil',
    appPreferences: 'Préférences de l\'App',
    personalInfo: 'Informations Personnelles',
    fullName: 'Nom Complet',
    emailAddress: 'Adresse Email',
    dateOfBirth: 'Date de Naissance',
    location: 'Localisation',
    saveChanges: 'Sauvegarder',
    cancel: 'Annuler',
    changePhoto: 'Changer la Photo',
    
    // App Preferences
    readingPreferences: 'Préférences de Lecture',
    pushNotifications: 'Notifications Push',
    soundEffects: 'Effets Sonores',
    autoBookmark: 'Marque-page Auto',
    enhancedReaderMode: 'Mode Lecture Amélioré',
    dailyReadingReminders: 'Rappels de Lecture Quotidiens',
    resetOptions: 'Options de Réinitialisation',
    resetReadingProgress: 'Réinitialiser le Progrès de Lecture',
    clearAllBookmarks: 'Effacer Tous les Marque-pages',
    resetAllPreferences: 'Réinitialiser Toutes les Préférences',
    
    // Notifications
    notificationSettings: 'Paramètres de Notification',
    readingReminders: 'Rappels de Lecture',
    achievements: 'Réalisations',
    weeklyDigest: 'Résumé Hebdomadaire',
    
    // About
    appVersion: 'Version de l\'App',
    rewardSystem: 'Système de Récompense',
    howToEarn: 'Comment Gagner',
    leaderboardInfo: 'Informations du Classement',
    
    // Success messages
    profileUpdated: 'Profil mis à jour avec succès!',
    addressCopied: 'Adresse copiée dans le presse-papiers!',
    
    // Descriptions
    pushNotificationsDesc: 'Recevez des notifications pour les rappels de lecture et les réalisations',
    soundEffectsDesc: 'Jouer des sons pour les interactions et les réalisations',
    autoBookmarkDesc: 'Marquer automatiquement votre progression de lecture',
    enhancedReaderModeDesc: 'Optimiser le texte pour une lecture confortable',
    dailyReadingRemindersDesc: 'Soyez rappelé de continuer votre lecture quotidienne'
  },
  
  es: {
    // Navigation
    home: 'Inicio',
    bible: 'Biblia',
    leaderboard: 'Clasificación',
    wallet: 'Billetera',
    profile: 'Perfil',
    
    // Settings
    settings: 'Configuración',
    notifications: 'Notificaciones',
    darkMode: 'Modo Oscuro',
    language: 'Idioma',
    privacy: 'Privacidad',
    about: 'Acerca de',
    
    // Profile
    editProfile: 'Editar Perfil',
    appPreferences: 'Preferencias de la App',
    personalInfo: 'Información Personal',
    fullName: 'Nombre Completo',
    emailAddress: 'Dirección de Email',
    dateOfBirth: 'Fecha de Nacimiento',
    location: 'Ubicación',
    saveChanges: 'Guardar Cambios',
    cancel: 'Cancelar',
    changePhoto: 'Cambiar Foto',
    
    // App Preferences
    readingPreferences: 'Preferencias de Lectura',
    pushNotifications: 'Notificaciones Push',
    soundEffects: 'Efectos de Sonido',
    autoBookmark: 'Marcador Automático',
    enhancedReaderMode: 'Modo de Lectura Mejorado',
    dailyReadingReminders: 'Recordatorios de Lectura Diaria',
    resetOptions: 'Opciones de Reinicio',
    resetReadingProgress: 'Reiniciar Progreso de Lectura',
    clearAllBookmarks: 'Limpiar Todos los Marcadores',
    resetAllPreferences: 'Reiniciar Todas las Preferencias',
    
    // Notifications
    notificationSettings: 'Configuración de Notificaciones',
    readingReminders: 'Recordatorios de Lectura',
    achievements: 'Logros',
    weeklyDigest: 'Resumen Semanal',
    
    // About
    appVersion: 'Versión de la App',
    rewardSystem: 'Sistema de Recompensas',
    howToEarn: 'Cómo Ganar',
    leaderboardInfo: 'Información de Clasificación',
    
    // Success messages
    profileUpdated: '¡Perfil actualizado exitosamente!',
    addressCopied: '¡Dirección copiada al portapapeles!',
    
    // Descriptions
    pushNotificationsDesc: 'Recibir notificaciones para recordatorios de lectura y logros',
    soundEffectsDesc: 'Reproducir sonidos para interacciones y logros',
    autoBookmarkDesc: 'Marcar automáticamente tu progreso de lectura',
    enhancedReaderModeDesc: 'Optimizar texto para lectura cómoda',
    dailyReadingRemindersDesc: 'Recibe recordatorios para continuar tu lectura diaria'
  },
  
  ar: {
    // Navigation
    home: 'الرئيسية',
    bible: 'الكتاب المقدس',
    leaderboard: 'المتصدرين',
    wallet: 'المحفظة',
    profile: 'الملف الشخصي',
    
    // Settings
    settings: 'الإعدادات',
    notifications: 'الإشعارات',
    darkMode: 'الوضع المظلم',
    language: 'اللغة',
    privacy: 'الخصوصية',
    about: 'حول',
    
    // Profile
    editProfile: 'تعديل الملف الشخصي',
    appPreferences: 'تفضيلات التطبيق',
    personalInfo: 'المعلومات الشخصية',
    fullName: 'الاسم الكامل',
    emailAddress: 'عنوان البريد الإلكتروني',
    dateOfBirth: 'تاريخ الميلاد',
    location: 'الموقع',
    saveChanges: 'حفظ التغييرات',
    cancel: 'إلغاء',
    changePhoto: 'تغيير الصورة',
    
    // App Preferences
    readingPreferences: 'تفضيلات القراءة',
    pushNotifications: 'الإشعارات الفورية',
    soundEffects: 'التأثيرات الصوتية',
    autoBookmark: 'إشارة مرجعية تلقائية',
    enhancedReaderMode: 'وضع القراءة المحسن',
    dailyReadingReminders: 'تذكيرات القراءة اليومية',
    resetOptions: 'خيارات إعادة التعيين',
    resetReadingProgress: 'إعادة تعيين تقدم القراءة',
    clearAllBookmarks: 'مسح جميع الإشارات المرجعية',
    resetAllPreferences: 'إعادة تعيين جميع التفضيلات',
    
    // Notifications
    notificationSettings: 'إعدادات الإشعارات',
    readingReminders: 'تذكيرات القراءة',
    achievements: 'الإنجازات',
    weeklyDigest: 'الملخص الأسبوعي',
    
    // About
    appVersion: 'إصدار التطبيق',
    rewardSystem: 'نظام المكافآت',
    howToEarn: 'كيفية الكسب',
    leaderboardInfo: 'معلومات المتصدرين',
    
    // Success messages
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
    addressCopied: 'تم نسخ العنوان إلى الحافظة!',
    
    // Descriptions
    pushNotificationsDesc: 'تلقي إشعارات للتذكيرات القراءة والإنجازات',
    soundEffectsDesc: 'تشغيل الأصوات للتفاعلات والإنجازات',
    autoBookmarkDesc: 'وضع إشارة مرجعية تلقائية لتقدم القراءة',
    enhancedReaderModeDesc: 'تحسين النص للقراءة المريحة',
    dailyReadingRemindersDesc: 'احصل على تذكيرات لمتابعة قراءتك اليومية'
  },
  
  zh: {
    // Navigation
    home: '首页',
    bible: '圣经',
    leaderboard: '排行榜',
    wallet: '钱包',
    profile: '个人资料',
    
    // Settings
    settings: '设置',
    notifications: '通知',
    darkMode: '深色模式',
    language: '语言',
    privacy: '隐私',
    about: '关于',
    
    // Profile
    editProfile: '编辑个人资料',
    appPreferences: '应用偏好',
    personalInfo: '个人信息',
    fullName: '全名',
    emailAddress: '电子邮件地址',
    dateOfBirth: '出生日期',
    location: '位置',
    saveChanges: '保存更改',
    cancel: '取消',
    changePhoto: '更改照片',
    
    // App Preferences
    readingPreferences: '阅读偏好',
    pushNotifications: '推送通知',
    soundEffects: '音效',
    autoBookmark: '自动书签',
    enhancedReaderMode: '增强阅读模式',
    dailyReadingReminders: '每日阅读提醒',
    resetOptions: '重置选项',
    resetReadingProgress: '重置阅读进度',
    clearAllBookmarks: '清除所有书签',
    resetAllPreferences: '重置所有偏好',
    
    // Notifications
    notificationSettings: '通知设置',
    readingReminders: '阅读提醒',
    achievements: '成就',
    weeklyDigest: '每周摘要',
    
    // About
    appVersion: '应用版本',
    rewardSystem: '奖励系统',
    howToEarn: '如何赚取',
    leaderboardInfo: '排行榜信息',
    
    // Success messages
    profileUpdated: '个人资料更新成功！',
    addressCopied: '地址已复制到剪贴板！',
    
    // Descriptions
    pushNotificationsDesc: '接收阅读提醒和成就通知',
    soundEffectsDesc: '为交互和成就播放声音',
    autoBookmarkDesc: '自动标记您的阅读进度',
    enhancedReaderModeDesc: '优化文本以便舒适阅读',
    dailyReadingRemindersDesc: '获取提醒以继续您的每日阅读'
  },
  
  pt: {
    // Navigation
    home: 'Início',
    bible: 'Bíblia',
    leaderboard: 'Classificação',
    wallet: 'Carteira',
    profile: 'Perfil',
    
    // Settings
    settings: 'Configurações',
    notifications: 'Notificações',
    darkMode: 'Modo Escuro',
    language: 'Idioma',
    privacy: 'Privacidade',
    about: 'Sobre',
    
    // Profile
    editProfile: 'Editar Perfil',
    appPreferences: 'Preferências do App',
    personalInfo: 'Informações Pessoais',
    fullName: 'Nome Completo',
    emailAddress: 'Endereço de Email',
    dateOfBirth: 'Data de Nascimento',
    location: 'Localização',
    saveChanges: 'Salvar Alterações',
    cancel: 'Cancelar',
    changePhoto: 'Alterar Foto',
    
    // App Preferences
    readingPreferences: 'Preferências de Leitura',
    pushNotifications: 'Notificações Push',
    soundEffects: 'Efeitos Sonoros',
    autoBookmark: 'Marcador Automático',
    enhancedReaderMode: 'Modo de Leitura Aprimorado',
    dailyReadingReminders: 'Lembretes de Leitura Diária',
    resetOptions: 'Opções de Redefinição',
    resetReadingProgress: 'Redefinir Progresso de Leitura',
    clearAllBookmarks: 'Limpar Todos os Marcadores',
    resetAllPreferences: 'Redefinir Todas as Preferências',
    
    // Notifications
    notificationSettings: 'Configurações de Notificação',
    readingReminders: 'Lembretes de Leitura',
    achievements: 'Conquistas',
    weeklyDigest: 'Resumo Semanal',
    
    // About
    appVersion: 'Versão do App',
    rewardSystem: 'Sistema de Recompensas',
    howToEarn: 'Como Ganhar',
    leaderboardInfo: 'Informações da Classificação',
    
    // Success messages
    profileUpdated: 'Perfil atualizado com sucesso!',
    addressCopied: 'Endereço copiado para a área de transferência!',
    
    // Descriptions
    pushNotificationsDesc: 'Receber notificações para lembretes de leitura e conquistas',
    soundEffectsDesc: 'Reproduzir sons para interações e conquistas',
    autoBookmarkDesc: 'Marcar automaticamente seu progresso de leitura',
    enhancedReaderModeDesc: 'Otimizar texto para leitura confortável',
    dailyReadingRemindersDesc: 'Receba lembretes para continuar sua leitura diária'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  const t = (key: string): string => {
    const lang = language as keyof typeof translations;
    const langTranslations = translations[lang] || translations.en;
    return langTranslations[key as keyof typeof langTranslations] || key;
  };

  const handleSetLanguage = (lang: string) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};